### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by kimryan505** [ds-civic-data/counting-the-homeless#1]
- [ ] email/make calls to contacts
- [ ] talk to Matthew Tschabold at Portland Housing Bureau
- [ ] meet with Kristin
- [ ] decide on deliverables
- [ ] be halfway done with project
- [ ] finish project
- [ ] posterboards
